[package]
name = "h2-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = "0.3.15"
http = "0.2.8"
tokio = { version = "1.25.0", features = [ "full" ] }
