[package]
name = "may_minihttp_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
may_minihttp = { git = "https://github.com/Xudong-Huang/may_minihttp.git" }